//! Writes the committed Matter onboarding artifacts, or checks them.
//!
//!   cargo run -p oci-zero-matter-qr            # regenerate
//!   cargo run -p oci-zero-matter-qr -- --check  # fail if stale
//!
//! CI runs the regenerate form and then `git diff --exit-code`, so changing the
//! commissioning constants fails the build until the README is regenerated.
use std::path::{Path, PathBuf};

use oci_zero_matter_qr::{onboarding, svg, text_qr};

const SVG_PATH: &str = "examples/esp32c3-ota/onboarding-qr.svg";
const TEXT_PATH: &str = "examples/esp32c3-ota/onboarding.txt";
const QR_TEXT_PATH: &str = "examples/esp32c3-ota/onboarding-qr.txt";

fn main() -> std::io::Result<()> {
    let check = std::env::args().any(|argument| argument == "--check");
    let root = repository_root();

    let data = onboarding();
    let svg_contents = svg(&data.payload);
    let text_contents = format!(
        "# Generated by `cargo run -p oci-zero-matter-qr`. Do not edit.\n\
         payload={}\n\
         manual_code={}\n\
         pretty_manual_code={}\n\
         vendor_id={}\n\
         product_id={}\n\
         discriminator={}\n\
         passcode={}\n",
        data.payload,
        data.manual_code,
        data.pretty_manual_code,
        data.vendor_id,
        data.product_id,
        data.discriminator,
        data.passcode,
    );

    let mut stale = Vec::new();
    for (path, contents) in [
        (SVG_PATH, svg_contents),
        (TEXT_PATH, text_contents),
        (QR_TEXT_PATH, text_qr(&data.payload)),
    ] {
        let absolute = root.join(path);
        if check {
            let current = std::fs::read_to_string(&absolute).unwrap_or_default();
            if current != contents {
                stale.push(path);
            }
        } else {
            std::fs::write(&absolute, contents)?;
            println!("wrote {path}");
        }
    }

    if check && !stale.is_empty() {
        eprintln!(
            "stale onboarding artifacts: {}\n\
             The commissioning constants changed. Run `cargo run -p oci-zero-matter-qr` \
             and commit the result.",
            stale.join(", "),
        );
        std::process::exit(1);
    }

    if !check {
        println!("\npayload:     {}", data.payload);
        println!("manual code: {}", data.pretty_manual_code);
        println!("\n{}", text_qr(&data.payload));
    }
    Ok(())
}

/// The crate lives at `tools/matter-qr`, so the repository root is two levels up
/// from its manifest. Derived rather than taken from the current directory, so the
/// output is the same however cargo was invoked.
fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("the crate is nested two levels below the repository root")
        .to_path_buf()
}
